### ISSUE TITLE
Provide a docker image

### ISSUE THREAD

**Issue by tsl0922** [Coding/WebIDE#10]
It would be nice to have a docker image for testing WebIDE, this will make life easier 😄

**Comment by hackape** [comment]
You're welcome to go ide.coding.net and give our product a try. ;)
------------------ Original ------------------

**Comment by vangie** [comment]
@tsl0922 docker 版本计划中，很快就有了。

**Comment by hackape** [comment]
link #19

**Comment by tanhe123** [comment]
now, docker image is provided in docker hub. 
refer to [readme](https://github.com/Coding/WebIDE/blob/master/README.md)
