### ISSUE TITLE
docker 安装之后，报错

### ISSUE THREAD

**Issue by fghpdf** [Coding/WebIDE#100]
## 系统信息

1. mac 10.12.3

2. Docker version 1.12.6, build 78d1802

## 安装步骤

1. 在 docker-machine default 里面按照 readme 执行的命令

2. 在浏览器可以打开

3. 添加了一个自己的项目，成功

4. 目前是在首页就会报错，进入项目如下图

![image](https://cloud.githubusercontent.com/assets/7081582/22319539/8767eaf0-e3be-11e6-8491-f220799062ef.png)

求解决方案

**Comment by biolee** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/7426917/23297433/7482cb1e-fab4-11e6-9b70-1ee8da706b41.png)

i got similar err

**Comment by pinewong** [comment]
+1

**Comment by vangie** [comment]
昨天有更新过 docker image，再试试？

**Comment by zhuruiqi** [comment]
没有复现，有问题可再次反馈。
![image](https://cloud.githubusercontent.com/assets/26532614/24999098/d7fdf6a2-206e-11e7-94cb-1e562c01b9a0.png)

**Comment by pinewong** [comment]
现在首页没有报错，但是 clone 项目后的 IDE 页会报错，会报 JS 错
![image](https://cloud.githubusercontent.com/assets/16538603/25041077/e87b56f6-213f-11e7-9583-16157016839d.png)
