### ISSUE TITLE
代码检出菜单的若干改进

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#103]
![597b517c-5d31-4284-95d8-aae3a7502f51](https://cloud.githubusercontent.com/assets/1388582/24086846/c940befe-0d51-11e7-87ff-0d48ee2e8cbe.png)

![image](https://cloud.githubusercontent.com/assets/1388582/24086872/1ed47748-0d52-11e7-94e6-e17d21802450.png)

**Comment by zhuruiqi** [comment]
最后一个样式没有改，其他没有问题。
![image](https://cloud.githubusercontent.com/assets/1388582/24086872/1ed47748-0d52-11e7-94e6-e17d21802450.png)

**Comment by blizzardzheng** [comment]
@zhuruiqi 就是图标太小了没有改？
