### ISSUE TITLE
新增 button 的改进

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#104]
1. '+' 不是居中的，目测向左偏移了一个像素
2. 鼠标 hover 的时候没有反馈

![snip20170320_3](https://cloud.githubusercontent.com/assets/1388582/24086921/b3925eae-0d52-11e7-951f-1ea06d84b062.png)
![snip20170320_4](https://cloud.githubusercontent.com/assets/1388582/24086922/be920e58-0d52-11e7-88dd-90f26787c134.png)

**Comment by zhuruiqi** [comment]
![image](https://cloud.githubusercontent.com/assets/26532614/24574728/a345bd22-16c9-11e7-9d1f-50d7931554c5.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24574769/221ebb80-16ca-11e7-81f6-a9f487bc0616.png)

**Comment by hackape** [comment]
对，这个我也发现了…
