### ISSUE TITLE
顶部菜单栏不醒目

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#107]
![image](https://cloud.githubusercontent.com/assets/26532614/24089688/58af446c-0d74-11e7-80e2-41e756243b6c.png)

**Comment by zhuruiqi** [comment]
![image](https://cloud.githubusercontent.com/assets/26532614/24574443/4836c16e-16c5-11e7-91e4-590748df9b95.png)
没怎么看出来区别，菜单栏字体小了点

**Comment by hackape** [comment]
@zhuruiqi 我加了个下边框，字号的话我是把整个应用的字号都相比旧版缩小了一号。醒不醒目这事儿没法说啊，都是主观感受…

**Comment by zhuruiqi** [comment]
OK，整个缩小了一号是吧，我了解了。
