### ISSUE TITLE
输入commit summary后，回车键不可commit

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#110]
![image](https://cloud.githubusercontent.com/assets/26532614/24090612/cde6e5e8-0d7c-11e7-9127-0774b105836a.png)

**Comment by hackape** [comment]
回车不可用是正确的行为，因为 commit summary 确实是可以多行的，需要回车。但这里应该考虑增加 ctrl/cmd+enter 作为确认。这个优先级下降一下。
