### ISSUE TITLE
文件夹右击菜单中的Download不可用

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#117]
![image](https://cloud.githubusercontent.com/assets/26532614/24093203/9750de92-0d8d-11e7-85ce-0dbf5268b6e9.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24093236/cd1a67be-0d8d-11e7-8de4-7fa3cb45d3ed.png)

**Comment by hackape** [comment]
我没有复现这个问题
@tanhe123 你看下这个报错信息？貌似是后端问题
