### ISSUE TITLE
重命名文件夹后，文件夹消失，刷新后才能再次显示

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#118]
![image](https://cloud.githubusercontent.com/assets/26532614/24093448/d396aa7a-0d8e-11e7-9e79-7ef3c9a43313.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24093484/0685e0a4-0d8f-11e7-8cad-21ff9bd57671.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24093511/20a71d5e-0d8f-11e7-9569-7cbef214ee87.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24093539/4f134afa-0d8f-11e7-91e1-79b18e0c98c4.png)

**Comment by hackape** [comment]
后端 ws-manager 多给了一条错误的删除事件，天高已经修了，未部署测试，我备注一下先。

**Comment by tanhe123** [comment]
fixed: https://coding.net/t/codingcorp/p/coding-ide-wsmgr/git/merge/57

**Comment by zhuruiqi** [comment]
等上线验证没有问题后，再关闭。需要回归时把 issue 指回给我即可。

**Comment by zhuruiqi** [comment]
经验证：fixed。
