### ISSUE TITLE
在任一分支中添加文件，所有分支都会出现该文件

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#119]
![image](https://cloud.githubusercontent.com/assets/26532614/24128815/552202d0-0e19-11e7-826f-c794a7d4e6e1.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24128886/ddc16dc4-0e19-11e7-9df6-d1f53d12f81b.png)

**Comment by hackape** [comment]
你创建后有 commit 进那个 branch 吗？如果没有的话，那这就是正常行为。如果 commit 后，切换分支还有这个文件那才不正常，我测试下来好像没问题

**Comment by hackape** [comment]
@zhuruiqi 有问题再还给我

**Comment by zhuruiqi** [comment]
@hackape 没问题啦。
