### ISSUE TITLE
Not sure the version of the dependency

### ISSUE THREAD

**Issue by owtotwo** [Coding/WebIDE#12]
nodejs, maven, babel and webpack... ( and JDK..)

**Comment by vangie** [comment]
We will add versions and dockerfile coming soon.

**Comment by hackape** [comment]
@owtotwo We've updated readmes lately. Also check into readme of [WebIDE-Frontend](https://github.com/Coding/WebIDE-Frontend) and [WebIDE-Backend](https://github.com/Coding/WebIDE-Backend) for more details.
