### ISSUE TITLE
新建分支对话框，键入回车后页面刷新，新分支创建失败

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#120]
![image](https://cloud.githubusercontent.com/assets/26532614/24132485/d4e634e8-0e30-11e7-8f0c-db11c65494b2.png)

![image](https://cloud.githubusercontent.com/assets/26532614/24129685/38eec9c6-0e1f-11e7-82ee-41692ad352b2.png)

**Comment by hackape** [comment]
这个挺神奇的，还没细看是什么原因…

**Comment by hackape** [comment]
Note: 原因是这里的回车没有进行处理，并且这个 input 是在一个 form 里头，所以浏览器的默认行为是回触发表格的 submit.
