### ISSUE TITLE
删除当前 checkout 的分支，仍提示删除成功

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#121]
![image](https://cloud.githubusercontent.com/assets/26532614/24130517/fe48914e-0e23-11e7-86c8-2f70558c797f.png)

**Comment by hackape** [comment]
其实是失败了，但因为 #139 前端误判为成功

**Comment by hackape** [comment]
合并 #139 到这里。

发现一个 API 格式问题：
DELETE /git/{spaceKey}/branches/{branchName}
带上 v2 的 Accept header，出错的情况下我得到的还是 v1 的格式的反馈，表现为 200 OK, 但内容却是 { code: -1, msg: ... }
