### ISSUE TITLE
checkout 远程分支失败

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#122]
![image](https://cloud.githubusercontent.com/assets/26532614/24130731/50e93452-0e25-11e7-95ec-bcb771a18252.png)

**Comment by hackape** [comment]
这个菜单项目已经被移除，功能与第二个菜单项合并（此入口已重命名为 Checkout as new **local** branch） 
ref to #123

**Comment by zhuruiqi** [comment]
点击没有反应
![image](https://cloud.githubusercontent.com/assets/26532614/24574566/8de57c30-16c7-11e7-82e5-32da9aa60524.png)

**Comment by hackape** [comment]
@blizzardzheng 修改 app/components/Git/GitBranchWidget.jsx
```
ln:76
command: () => dispatchCommand('git:checkout_new_branch', {
  fromBranch: branch
})

ln: 90
command: () => dispatchCommand('git:checkout_new_branch', {
  fromBranch: remoteBranch,
  toBranch: localBranch
})
```
