### ISSUE TITLE
对分支操作【checkout as new branch 】，创建的分支与当前分支一致，应与源分支一致

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#123]
![image](https://cloud.githubusercontent.com/assets/26532614/24132629/03312f00-0e32-11e7-8f4c-05b4260c9291.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24132710/7ee03ce0-0e32-11e7-8454-80ecb7c7d3e7.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24132613/e6ea4e76-0e31-11e7-9eae-29bc1e31983b.png)

备注：
此处不应该弹出此对话框
![image](https://cloud.githubusercontent.com/assets/26532614/24131463/c7c6a010-0e29-11e7-89a3-4543bcee1a8d.png)
应弹出类似这样的对话框
![image](https://cloud.githubusercontent.com/assets/26532614/24132688/59bfda9c-0e32-11e7-9b7e-a4815f6c7f12.png)

**Comment by blizzardzheng** [comment]
这里其实是对的，check out as a new branch 就是新建一个分支checkout，我必须输入新分支名字，和创建分支一样。这个选项和这个选项上面一个checkout 的业务逻辑不同。上面一个是checkout到当前分支，

**Comment by zhuruiqi** [comment]
@blizzardzheng 这里弹出的创建分支对话框应该是类似这样的
![image](https://cloud.githubusercontent.com/assets/26532614/24132069/96385a08-0e2d-11e7-9a3a-ba84933699ee.png)
这里的业务逻辑与当前分支没有关系，创建的新分支应该与源分支一致，而不是与当前分支一致。如上图，我对newbranch执行checkout as new branch，那么我检出的分支应与newbranch内容一致，而不是与当前分支master一致。

**Comment by hackape** [comment]
这个 modal 的文案确实有误导性，要改一下

**Comment by zhuruiqi** [comment]
![image](https://cloud.githubusercontent.com/assets/26532614/24574631/6be10c48-16c8-11e7-9eea-e9f8d8034bae.png)

**Comment by hackape** [comment]
这个跟 #122 是同一个问题，看那边就好。@zhuruiqi 要不这边先关了？

**Comment by zhuruiqi** [comment]
@hackape 先别关，这个是那边的问题导致的这边无法测试，但不是同一个问题。
