### ISSUE TITLE
处理冲突文件页，箭头显示问题

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#125]
![image](https://cloud.githubusercontent.com/assets/26532614/24136052/f7d17d70-0e47-11e7-989b-a981e0d0dbff.png)

**Comment by hackape** [comment]
这个 merge tool 不是自己实现的，是直接用的 CodeMirror 提供的插件，改起来有点难。这问题优先级太低，暂时忽略吧…

**Comment by zhuruiqi** [comment]
先别关，这个确实优先级比较低，所以我挂在我名下的，继续挂在我名下好了。

**Comment by vangie** [comment]
上游控件如此
