### ISSUE TITLE
文件保存问题

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#127]
2个问题：
1、modify 文件后执行git status，提示 working directory clean（这样就无法commit了）
![image](https://cloud.githubusercontent.com/assets/26532614/24136559/57b45526-0e4a-11e7-8abd-07747ebd1ead.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24136775/618de94e-0e4b-11e7-9f1f-a2097bf6e0c3.png)
2、新建文件、输入内容并commit，关闭文件再打开后，文件内容没有保存
![image](https://cloud.githubusercontent.com/assets/26532614/24137663/c9a01508-0e4f-11e7-9e5e-45c4aa54e1c2.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24137918/e85accd0-0e50-11e7-935d-e17b6ffc33b2.png)

**Comment by zhuruiqi** [comment]
这个比较严重，把恢复代码、储藏代码部分的流程block住了

**Comment by hackape** [comment]
这个是因为没有默认开启自动保存，这版的设定是需要手动 cmd+s 才保存。我还是默认开启自动保存吧。

**Comment by zhuruiqi** [comment]
等上线验证没有问题后，再关闭。需要回归时把 issue 指回给我即可。
