### ISSUE TITLE
合并分支对话框的显示问题

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#130]
![image](https://cloud.githubusercontent.com/assets/26532614/24180054/b53e08b0-0eed-11e7-8996-f88a34c129c9.png)

**Comment by zhuruiqi** [comment]
![image](https://cloud.githubusercontent.com/assets/26532614/24574357/e3b24688-16c3-11e7-99c9-36ec25deb442.png)

还是有个空格，只不过跑上面去了。

**Comment by hackape** [comment]
http://stackoverflow.com/questions/8605516/default-select-option-as-blank
