### ISSUE TITLE
有冲突时合并分支，

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#131]
步骤：
1、在分支 branch1 上添加文件 file2 ，内容为“11111”；
![image](https://cloud.githubusercontent.com/assets/26532614/24181979/64e81f20-0ef9-11e7-8799-b4d45a4d1e0a.png)
2、在分支 branch2 上添加文件 file2， 内容为"22222";
![image](https://cloud.githubusercontent.com/assets/26532614/24181996/7c971e14-0ef9-11e7-80fc-347bcd1dad4c.png)
3、合并分支，没有弹出解决冲突对话框。
![image](https://cloud.githubusercontent.com/assets/26532614/24182136/a74e8dee-0efa-11e7-93a1-a00649a07aab.png)

V1下：
![image](https://cloud.githubusercontent.com/assets/26532614/24182210/1da93d72-0efb-11e7-929c-7f3bf1c030e5.png)

**Comment by hackape** [comment]
目测跟 #132 一样原因

**Comment by zhuruiqi** [comment]
发现另一个问题。#147
