### ISSUE TITLE
Unstash Changes 失败

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#132]
1、输入 file5 内容“111111”并commit；
2、修改 file5 内容为“111111 222222”并Stash Changes；
3、打开 Unstash Changes 对话框，点击【View】，点击【Apply】。
![image](https://cloud.githubusercontent.com/assets/26532614/24183644/9c680af4-0f04-11e7-8a2e-7ad19173a862.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24183963/574ced98-0f06-11e7-83b2-2197fe49df12.png)

V1版本下
![image](https://cloud.githubusercontent.com/assets/26532614/24184352/7b8efc08-0f08-11e7-8fce-81dcade3a245.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24184455/fcd5fadc-0f08-11e7-87c9-922305467504.png)

**Comment by hackape** [comment]
看上去应该是 editor 没有响应文件变化，subscribeToFileChange 里的 modify case 之前遗漏，昨天已经加了，很可能已经本地修好，稍后检查

**Comment by hackape** [comment]
这原因是缺了一块大功能，editor 跟文件内容变化之间的联动没有建立。

**Comment by zhuruiqi** [comment]
Unstash Changes 报错失败
![image](https://cloud.githubusercontent.com/assets/26532614/24575024/6d031afc-16ce-11e7-8d54-694d2c872d20.png)

**Comment by hackape** [comment]
这个是后端问题， @tanhe123 修好了说一声吧

**Comment by tanhe123** [comment]
@hackape 把错误信息显示出来即可

**Comment by hackape** [comment]
错误信息我另外建一个issue吧，这个算完成了
