### ISSUE TITLE
对文件变化 websocket 消息的响应需要优化

### ISSUE THREAD

**Issue by hackape** [Coding/WebIDE#133]
现在已知问题有：
1. 当一个文件正在编辑时，可以从文件树上删除这个文件，但联动的 breadcrumb, editor, tab 都会出问题
2. gitStatus 状态改变并没有反应在文件树上

**Comment by vangie** [comment]
@hackape 这个 Issue 可以 close 了么？

**Comment by hackape** [comment]
@vangie 没，这个涉及面比较广…

**Comment by hackape** [comment]
#189

**Comment by hackape** [comment]
#188
