### ISSUE TITLE
./ide.sh run Failed~~

### ISSUE THREAD

**Issue by szy0syz** [Coding/WebIDE#14]
root@ubuntu:/home/szy0syz/WebIDE# ./ide.sh build
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Results :
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] --- maven-jettygzip-plugin:0.0.4:process (default) @ frontend ---
[INFO] Compressing static resources with gzip...
[INFO] Compressed file index.html. 993 -> 658
[INFO] Compressed file 1.1.js. 4486918 -> 1060176
[INFO] Compressed file favicon.ico. 4286 -> 681
[INFO] Compressed file main.js. 1225999 -> 348120
[INFO] 
[INFO] --- maven-jar-plugin:2.2:jar (default-jar) @ frontend ---
[INFO] Building jar: /home/szy0syz/WebIDE/frontend-webjars/target/frontend-1.0.0.jar
[INFO] 
[INFO] --- maven-install-plugin:2.3:install (default-install) @ frontend ---
[INFO] Installing /home/szy0syz/WebIDE/frontend-webjars/target/frontend-1.0.0.jar to /root/.m2/repository/net/coding/ide/frontend/1.0.0/frontend-1.0.0.jar
[INFO] Installing /home/szy0syz/WebIDE/frontend-webjars/pom.xml to /root/.m2/repository/net/coding/ide/frontend/1.0.0/frontend-1.0.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.537s
[INFO] Finished at: Sat Sep 17 22:37:42 CST 2016
[INFO] Final Memory: 11M/28M
[INFO] ------------------------------------------------------------------------

root@ubuntu:/home/szy0syz/WebIDE# ./ide.sh run
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Coding IDE Backend 0.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ backend ---
[INFO] Deleting /home/szy0syz/WebIDE/backend/target
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) @ backend >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ backend ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 10 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ backend ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 115 source files to /home/szy0syz/WebIDE/backend/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.106s
[INFO] Finished at: Sat Sep 17 22:38:35 CST 2016
[INFO] Final Memory: 16M/40M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project backend: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

求教~~~

**Comment by szy0syz** [comment]
nodejs version: 5.6.0 ，npm version: 3.6.0，Apache Maven 3.0.5，webpack 1.13.2
完全不懂maven~~

**Comment by tanhe123** [comment]
可以执行： mvn -v
查看 java version 是否为 1.8

**Comment by yhl3692319** [comment]
@szy0syz 我原来是jdk1.7的也遇到这个问题，升级到jdk1.8解决了。

```
wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u71-b15/jdk-8u71-linux-x64.tar.gz
sudo mkdir /opt/jdk
sudo tar -zxf jdk-8u71-linux-x64.tar.gz -C /opt/jdk/
rm jdk-8u71-linux-x64.tar.gz

sudo update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_71/bin/java 1
sudo update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_71/bin/javac 1

选择java版本
sudo update-alternatives --config java
sudo update-alternatives --config javac

java -version
javac -version
```

详见：[moving-from-jdk-1-7-to-jdk-1-8-on-ubuntu](http://stackoverflow.com/questions/30177455/moving-from-jdk-1-7-to-jdk-1-8-on-ubuntu)

**Comment by szy0syz** [comment]
@yhl3692319 @tanhe123 多些两位。
---------------------------------------------
现在能跑起来，但打地址进去页面是空白的？。
chrome的console提示？

main.js:32 Uncaught Error: Cannot find module "!!./../../node_modules/css-loader/index.js?sourceMap!./../../node_modules/sass-loader/index.js?sourceMap!./main.scss"(anonymous function) @ main.js:32(anonymous function) @ main.js:32t @ main.js:1(anonymous function) @ main.js:1t @ main.js:1(anonymous function) @ main.js:1(anonymous function) @ main.js:1

**Comment by tanhe123** [comment]
更新下代码，试试，应该已经修复了

```
git pull 
git submodule update
```

**Comment by szy0syz** [comment]
@tanhe123 更新了最新版，还有点小问题~
`2016-09-20 15:12:14.672  WARN 7318 --- [           main] org.atmosphere.cpr.AtmosphereFramework   : SessionSupport error. Make sure you also define org.atmosphere.cpr.SessionSupport as a listener in web.xml, see https://github.com/Atmosphere/atmosphere/wiki/Enabling-HttpSession-Support`

![qq 20160920151420](https://cloud.githubusercontent.com/assets/10555820/18660764/ed2cc6be-7f44-11e6-927d-4552f2c9f3a8.png)

**Comment by tanhe123** [comment]
默认是有 CORS 的配置的
尝试添加 192.168.2.144:8080 到项目下的 src/main/resources/application.yml 中的 ALLOWED_ORIGINS

**Comment by szy0syz** [comment]
我加上了，还是一样的问题￥。￥

**Comment by tanhe123** [comment]
这个 warn 是没有问题的，可以忽略
现在的问题是页面可以显示，但是无法操作吗？

**Comment by linv2** [comment]
再main.js文件内50712行 指定的baseUrl值固定为"http://localhost:8080/"
导致获取不到public key和请求工作空间出错

**Comment by tanhe123** [comment]
@linv2 非常感谢你的回复，这个问题已经修复，会随着 docker 版一起发布 #22

**Comment by tanhe123** [comment]
已经修复了
