### ISSUE TITLE
交互变基中，Squash 操作问题

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#140]
1、新建分支 branch1，添加文件 A；
2、复制分支 branch1，重命名为 branch2，此时 branch2 中也有文件 A；
3、分支 branch2 中添加文件 B 并提交，添加文件 C 并提交，此时 branch2 中有文件 A、B、C；
4、分支 branch1 中添加文件 D 并提交，此时 branch1 中有文件A、D；
5、交互变基，文件 C 的 commit 选择 Squash 方式。
![image](https://cloud.githubusercontent.com/assets/26532614/24230345/8ef9e7f6-0fb9-11e7-8552-a4445d9f715b.png)

![image](https://cloud.githubusercontent.com/assets/26532614/24230326/6ee5282c-0fb9-11e7-87f2-2a93592462f1.png)

**Comment by tanhe123** [comment]
https://coding.net/t/codingcorp/p/coding-ide/git/merge/1895

**Comment by zhuruiqi** [comment]
有个报错
![image](https://cloud.githubusercontent.com/assets/26532614/24575252/24698060-16d3-11e7-9047-5b30f2e2b069.png)

**Comment by zhuruiqi** [comment]
执行以上步骤后，查看history，没有体现出 SQUASH 操作
![image](https://cloud.githubusercontent.com/assets/26532614/24948988/b2cb64da-1f9e-11e7-8bd4-9312020c8983.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24949018/cb282cca-1f9e-11e7-8589-c05c7ca7a0b6.png)

**Comment by tanhe123** [comment]
@KevenYoung 需要刷新 history 标签页
