### ISSUE TITLE
git 切换分支后，变动的文件的 gitStatus 状态不正确

### ISSUE THREAD

**Issue by hackape** [Coding/WebIDE#142]

**Comment by hackape** [comment]
补充两个现象：
1. git commit 一个新文件之后，它的文件状态并不会从 added 变成 clean，ws 上收不到消息变化。
2. 从 branch_a checkout 到 branch_b 的时候，(此时 HEAD is clean) 容易出现 ws 上返回的文件 gitStatus 是HEAD~1 到 HEAD 被 commit 之前的文件状态，比如 modified, added，这种，理论上在 commit 之后都应该消失的状态还会保留着。这个现象不可稳定复现，貌似来回切换几次分支就会又正常了。

**Comment by tanhe123** [comment]
第一个没想到好的方案，因为提交文件时，文件本身并没有变化，变化的是`分支指针`以及 objects 中的内容，objects 中的变动是被忽略的，最多只能做到前端收到分支更新，刷新文件树，但这个方案不太好。
