### ISSUE TITLE
codemirror theme fix

### ISSUE THREAD

**Issue by hackape** [Coding/WebIDE#145]
默认的 ambience 白色主题不带代码高亮色，需要换一个有颜色的主题。另外 setting 里面 editor theme 的下拉框默认选中项目是错的。

**Comment by zhuruiqi** [comment]
这个我不是特别明白， @hackape 麻烦看一下？貌似是没好？
![image](https://cloud.githubusercontent.com/assets/26532614/24575636/7c0218b8-16de-11e7-83f4-ee27d00416df.png)

**Comment by hackape** [comment]
@zhuruiqi 这个是好的，因为你建的文件没有后缀名，它猜不到是什么语言，你可以试试看加个 .py

**Comment by zhuruiqi** [comment]
没有用哎
![image](https://cloud.githubusercontent.com/assets/26532614/24694761/bc972eec-1a15-11e7-947e-0808dd74f515.png)
