### ISSUE TITLE
the request of a dependency is an expression codemirror

### ISSUE THREAD

**Issue by shook2012** [Coding/WebIDE#146]
```
WARNING in ./~/codemirror/addon/mode/loadmode.js
Critical dependencies:
51:6-19 the request of a dependency is an expression
 @ ./~/codemirror/addon/mode/loadmode.js 51:6-19
```

./ide.sh build时，报Warning

**Comment by shook2012** [comment]
Request URL:http://172.17.231.101:8080/node_modules/codemirror/lib/codemirror.css
Request Method:GET
Status Code:404

**Comment by hackape** [comment]
@shook2012 warning 跟这个错误无关，已经修复。请重新 pull 下代码，并执行 `git submodule update` 再 build 试试看。
