### ISSUE TITLE
settings 的使用问题

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#150]
没有一一排查，但很多都设置了没有效果
![image](https://cloud.githubusercontent.com/assets/26532614/24575688/ca8fbef8-16df-11e7-99a3-14a527d83a98.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24575693/e3114d16-16df-11e7-9b29-794292899dbf.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24575823/e25fb404-16e2-11e7-9d5c-50231091a1d2.png)

**Comment by hackape** [comment]
重构了 setting module， 部分解决改 issue，现剩下 editor 的设置没有联动，由于从 ace 转到 codemirror 这块需要整体重做。拆分新的任务做记录 #179

**Comment by zhuruiqi** [comment]
#182
