### ISSUE TITLE
双击边栏标题文字会被选中

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#153]
![image](https://cloud.githubusercontent.com/assets/1388582/24687415/1a80975c-19ec-11e7-8efb-66290b13e3d9.png)

**Comment by zhuruiqi** [comment]
这里也需要处理一下
![image](https://cloud.githubusercontent.com/assets/26532614/24951554/651ba1f6-1fa7-11e7-9553-f24ef1b446af.png)

**Comment by zhuruiqi** [comment]
还有这里
![image](https://cloud.githubusercontent.com/assets/26532614/24992563/a9f147d8-2054-11e7-8cf9-f21944d4e1a5.png)
