### ISSUE TITLE
增加国际化支持

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#159]
1. 添加国际化支持框架
2. 支持语言特性：单复数，人称属性，性别属性等
3. 支持时间格式
4. 有独立的语言资源文件
5. （Optional） 插件化，比如中文繁体可以考虑插件化

**Comment by zhuruiqi** [comment]
还需增加：
1、文件树右击菜单
![image](https://user-images.githubusercontent.com/26532614/28458461-5ba051c4-6e3c-11e7-87c1-684b9452e93d.png)
2、提示语
![image](https://user-images.githubusercontent.com/26532614/28458478-6ddb07f8-6e3c-11e7-98c0-894e3c2bba75.png)
3、版本下的二级对话框
![image](https://user-images.githubusercontent.com/26532614/28458557-b170d7fe-6e3c-11e7-8464-00984a5c3fe6.png)

**Comment by zhuruiqi** [comment]
2处翻译错误
![image](https://user-images.githubusercontent.com/26532614/28812663-48a8a4c4-76c8-11e7-8c9d-e9755c31adfe.png)
![image](https://user-images.githubusercontent.com/26532614/28812673-531d71c8-76c8-11e7-8a23-650368c625b6.png)

**Comment by zhuruiqi** [comment]
#260
