### ISSUE TITLE
workspace创建

### ISSUE THREAD

**Issue by misshy** [Coding/WebIDE#16]
请问后台workspace的创建是 为每个用户创建， 还是为每个组创建？

**Comment by stiangao** [comment]
不太理解你问题的意思， WebIDE 会在当前用户目录下的 .coding-ide-home/workspace 中创建项目

**Comment by misshy** [comment]
@stiangao  请问如何实现协同开发，对一组用户来说，又如何创建workspace。

**Comment by stiangao** [comment]
通过网页访问本身就是可以多开的，文件的变化会通过 websocket 推送到所有打开的浏览器端，所以一个人创建一个 workspace 其他人可以直接访问。不过我们还没仔细考虑过协同开发的场景，不知道这么回答能解答你的问题不

**Comment by vangie** [comment]
@misshy 开源版本没有 group 的概念，每一个用户编辑的是自己对于 code repository 的一份代码拷贝，可以通过 git repo 来实现协作，和传统ide一样。目前并没有实现协同的功能。
