### ISSUE TITLE
nginx 反向代理以后，通过域名访问创建项目报错

### ISSUE THREAD

**Issue by qixin1991** [Coding/WebIDE#164]
WebIDE 跑在 Docker里面:

```
docker run --name webide-coding -p 9090:8080 -v $PWD/.coding-ide-home:/home/coding/.coding-ide-home -d webide/webide
```

直接使用IP没有问题

*Nginx配置*
```
server {
    listen 443 ssl http2;
    server_name 马赛克域名;

    ssl_certificate /etc/letsencrypt/live/马赛克域名/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/马赛克域名/privkey.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_prefer_server_ciphers on;
    ssl_stapling on;

    root /var/www/html;

    location / {
         proxy_headers_hash_max_size 51200;
         proxy_headers_hash_bucket_size 6400;
         proxy_set_header Host  $host;
         proxy_set_header X-Forwarded-For $remote_addr;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_pass http://172.20.9.1:9090;
    }
}
```

域名访问服务，创建`workspace`会一直卡在 `95%`那不动，使用内网IP `http://172.20.9.1:9090`访问可以正常创建服务。在IP方式服务创建成功后，使用域名方式访问，打开项目也会报错：

 ![图片](https://dn-coding-net-production-pp.qbox.me/59b8a448-8e70-43ce-9fa7-049cf442e7ce.png) 

 ![图片](https://dn-coding-net-production-pp.qbox.me/f6f29efe-56d8-4390-b805-f29ef388c6e4.png) 

 ![图片](https://dn-coding-net-production-pp.qbox.me/51b08365-f45a-43fd-babb-c099965ba1ff.png)

**Comment by tanhe123** [comment]
这是一个 CORS 问题，chrome 在请求时，即使是同源，也会发送 Origin 头，所以这就导致了问题。
这个在已经提交了 pr 修复了，参见 https://github.com/Coding/WebIDE-Backend/pull/19

另外使用你的 nginx 配置还需要加上这样的配置，来让 websocket 有效：

```
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
```
