### ISSUE TITLE
Rebase branch 对话框显示问题 

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#171]
![image](https://cloud.githubusercontent.com/assets/26532614/24951627/a66469ea-1fa7-11e7-9b37-2120dc4f43f8.png)

**Comment by hackape** [comment]
这个应该修了吧？@zhuruiqi 测试一下如果修了就关掉

**Comment by zhuruiqi** [comment]
not fixed。
![image](https://cloud.githubusercontent.com/assets/26532614/25741325/cad995d0-31bc-11e7-9bde-6031af294b83.png)

**Comment by zhuruiqi** [comment]
fixed。
