### ISSUE TITLE
开源版下，切换分支后，文件列表不显示当前分支的文件

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#172]
![image](https://cloud.githubusercontent.com/assets/26532614/24996084/18d18de8-2064-11e7-9cc0-9947d0e81202.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24996174/6b1ab61a-2064-11e7-8eda-1866b8a23b13.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24996183/7e7693aa-2064-11e7-81fd-7fa32db7459b.png)

**Comment by hackape** [comment]
实测已修复。
