### ISSUE TITLE
切换分支后，文件的内容没有随之变化

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#173]
1、新建分支 branch1，添加文件 A ，内容为111111，并 commit；
2、复制分支 branch1，并重命名为 branch2，修改内容文件 A 的内容为 222222，并 commit；
3、在分支 branch2 上打开文件 A，checkout 到 branch1 后，文件 A 的内容没有变为 111111，依然为222222。
![image](https://cloud.githubusercontent.com/assets/26532614/24996791/d68d1012-2066-11e7-873c-6e827a12af67.png)
![image](https://cloud.githubusercontent.com/assets/26532614/24996842/ff74d42e-2066-11e7-9480-304603d7c01a.png)

**Comment by hackape** [comment]
#183

**Comment by hackape** [comment]
#188

**Comment by hackape** [comment]
track #259

**Comment by zhuruiqi** [comment]
fixed
