### ISSUE TITLE
Editor Settings 对 CodeMirror 重新适配

### ISSUE THREAD

**Issue by hackape** [Coding/WebIDE#179]
![image](https://cloud.githubusercontent.com/assets/26532614/24575823/e25fb404-16e2-11e7-9d5c-50231091a1d2.png)

**Comment by hackape** [comment]
#188

**Comment by zhuruiqi** [comment]
1、隐藏文件功能不可用
![image](https://user-images.githubusercontent.com/26532614/29406782-af6d2dc0-8374-11e7-8d78-83e28dbfb6cc.png)
2、代码着色中，monokai、material 无法选中
![image](https://user-images.githubusercontent.com/26532614/29407277-78705bb0-8376-11e7-810e-8e415147604a.png)

**Comment by zhuruiqi** [comment]
fixed
