### ISSUE TITLE
右击文件夹，操作列表无法消除

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#181]
![image](https://cloud.githubusercontent.com/assets/26532614/25520727/952c7390-2c2f-11e7-8bfb-98f3591246ac.png)

![image](https://cloud.githubusercontent.com/assets/26532614/25520652/41fd76a6-2c2f-11e7-9400-a48898984aa9.png)

**Comment by hackape** [comment]
fixed
