### ISSUE TITLE
支持从 coding 跳转到 IDE

### ISSUE THREAD

**Issue by tanhe123** [Coding/WebIDE#198]
https://ide.coding.net/ws/?ownerName=codingcorp&projectName=coding-ide

先拿 ownerName 和 projectName 去查 find 接口，如果返回 spaceKey 则跳转，否则接着去查 hardware 接口拿到可用硬件配置 render modal，点确定后创建新的 workspace

**Comment by hackape** [comment]
fixed in https://github.com/Coding/WebIDE-Frontend/pull/123
