### ISSUE TITLE
Firefox 及 IE 浏览器下的页面显示问题

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#204]
Firefox
![image](https://user-images.githubusercontent.com/26532614/27668013-1c647a2c-5cb1-11e7-9056-1845761d1179.png)

IE
![image](https://user-images.githubusercontent.com/26532614/27667710-3ed07572-5caf-11e7-846e-085a1aca4f96.png)

**Comment by hackape** [comment]
这个可以关了吧？

**Comment by zhuruiqi** [comment]
#229
