### ISSUE TITLE
tab 右键菜单的垂直分窗和水平分窗有问题

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#209]
![image](https://user-images.githubusercontent.com/1388582/28298252-ba878a58-6ba4-11e7-9879-d8f958253f96.png)

并且控制台有报错

**Comment by zhuruiqi** [comment]
先水平/垂直分窗，再垂直/水平分窗，会卡住
![image](https://user-images.githubusercontent.com/26532614/28399521-20855028-6d40-11e7-8a3c-7ec8bc262812.png)

**Comment by zhuruiqi** [comment]
fixed
