### ISSUE TITLE
上传文件时，不显示上传状态

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#212]
https://codingcorp.coding.net/api/project/4024/files/39949/imagePreview
![image](https://user-images.githubusercontent.com/26532614/28966059-a24a6776-7946-11e7-82c1-2e87aed05850.png)

**Comment by zhuruiqi** [comment]
上传了 9 个文件，一些文件显示在文件树里面，一些没显示。

**Comment by tanhe123** [comment]
新文件没显示的 bug，已经修复

**Comment by zhuruiqi** [comment]
fixed
