### ISSUE TITLE
关闭文件 tab，文件内容仍存在

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#215]
1、未命名的文件
![image](https://user-images.githubusercontent.com/26532614/28303075-bbd348ec-6bc3-11e7-81cf-c9a0874ebb67.png)
![image](https://user-images.githubusercontent.com/26532614/28303102-dbc3ffb6-6bc3-11e7-9542-03ea8da41aac.png)
2、命名后的文件
![image](https://user-images.githubusercontent.com/26532614/28303195-622548da-6bc4-11e7-9b04-13a7279450bc.png)
![image](https://user-images.githubusercontent.com/26532614/28303201-7029be7a-6bc4-11e7-98e9-feb151a28511.png)

**Comment by hackape** [comment]
fixed
