### ISSUE TITLE
添加一个无文件名称的 tab，再右击文件夹选择【new file】，后一个无法输文件内容（偶现）

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#218]
![image](https://user-images.githubusercontent.com/26532614/28303869-c3252788-6bc7-11e7-9cf6-33b8bd29b625.png)
![image](https://user-images.githubusercontent.com/26532614/28303922-087a66a4-6bc8-11e7-8cce-9b121d943e9e.png)

![image](https://user-images.githubusercontent.com/26532614/28303850-ab653e76-6bc7-11e7-878c-5d755162ec38.png)

**Comment by hackape** [comment]
fixed
