### ISSUE TITLE
多次双击文件名会打开多个文件编辑 tab，已打开的文件不应被多次打开，应定位到已打开的 tab 

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#222]
![image](https://user-images.githubusercontent.com/26532614/28359865-3aaf1e24-6ca6-11e7-8511-c2ac86ac6f47.png)

**Comment by hackape** [comment]
track #259

**Comment by zhuruiqi** [comment]
待 #259 完成后测试

**Comment by zhuruiqi** [comment]
fixed
