### ISSUE TITLE
开源版markdown还是无法预览

### ISSUE THREAD

**Issue by liwangmj** [Coding/WebIDE#239]
用的docker镜像，最新的v0.13.1版本

![selection_001](https://user-images.githubusercontent.com/2976366/28599863-9698bc2e-71e0-11e7-911f-6a79f01e9101.png)

**Comment by zhuruiqi** [comment]
您好，该问题已经在 v0.14.0 中修复
![image](https://user-images.githubusercontent.com/26532614/29502859-b76f26e2-8665-11e7-8d41-7e775ca05a58.png)
