### ISSUE TITLE
菜单中有二级弹窗的操作需要加上“...”

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#254]
![image](https://user-images.githubusercontent.com/26532614/28816933-2c9e4868-76d9-11e7-820c-ac6a9a324227.png)
![image](https://user-images.githubusercontent.com/26532614/28816953-41145594-76d9-11e7-80c8-acad6172603e.png)
![image](https://user-images.githubusercontent.com/26532614/28817024-86cfbb28-76d9-11e7-8a7e-6d6078ccfc24.png)

**Comment by blizzardzheng** [comment]
@zhuruiqi 这个应该修复了吧

**Comment by zhuruiqi** [comment]
文件夹与文件的右击菜单没有修复
![image](https://user-images.githubusercontent.com/26532614/31601213-b645a1e0-b28b-11e7-8715-b60cda488bc7.png)
![image](https://user-images.githubusercontent.com/26532614/31601218-bc404c3a-b28b-11e7-9b95-862feeb75d24.png)

**Comment by zhuruiqi** [comment]
done
