### ISSUE TITLE
编辑器光标跳转

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#263]
1. 在状态栏显示光标的当前行列
2. 点击状态栏行列值出现跳转框（这个跳转框加个快捷键）

![image](https://user-images.githubusercontent.com/1388582/29101242-80acd202-7ce3-11e7-9883-90529279fa13.png)

**Comment by KevenYoung** [comment]
Done

**Comment by zhuruiqi** [comment]
#273
