### ISSUE TITLE
 Git 提交 msg 默认值

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#264]
![cc36d99c986433d2fba0ddf93c3d4672](https://user-images.githubusercontent.com/1388582/29101893-064fcc6c-7ce8-11e7-829f-1546cc3265e1.png)

如果不写默认值为，

英文：`update by Coding WebIDE ,  https://ide.coding.net`
中文：`由 Coding WebIDE 更新，https://ide.coding.net`

**Comment by zhuruiqi** [comment]
fixed
