### ISSUE TITLE
兼容 editconfig 规范

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#271]
1. 兼容 http://editorconfig.org/ ，针对每一个打开的编辑器 tab 都应用一下 editconfig 的规则。
2. 监听 editconfig 事件，如果文件发生变化，重新解析规则文件，如果解析失败，给出错误提示，并保留上一次解析结果。
3. editconfig 的设置优先级比 UI 界面的设置优先级高。

**Comment by zhuruiqi** [comment]
done #294
