### ISSUE TITLE
火狐浏览器下，无法拖拽文件

### ISSUE THREAD

**Issue by zhuruiqi** [Coding/WebIDE#283]
![image](https://user-images.githubusercontent.com/26532614/29911289-e82dc0c0-8e5f-11e7-801b-ebafd6eebbdd.png)
![image](https://user-images.githubusercontent.com/26532614/29911317-061cd684-8e60-11e7-8793-14dc0ee92a3b.png)

**Comment by vangie** [comment]
已经修复
