### ISSUE TITLE
如何才能搭建像live demo一样完善的社区版webide？

### ISSUE THREAD

**Issue by ladyrick** [Coding/WebIDE#289]
社区版webide默认搭建完之后，实在是太简陋呀，各种问题，各种bug。例如：
终端不能使用python，node，g++，gcc，等等。
主题是黑色的，第一个终端也是黑的，新建终端却是白的。
右侧三个按钮都没有，至少有个选择环境的吧。
左上角的洋葱猴图标不显示，但是点击还能出来设置

**Comment by vangie** [comment]
目前开源的前端是正式版本的主体部分，有部分插件并没有开源，如果有商业需要可以关注，https://ide.coding.net/enterprise。

图标不显示的问题可能是最近引入的 bug，我们查一下。
