### ISSUE TITLE
没有后缀的文件无法识别

### ISSUE THREAD

**Issue by bangbang93** [Coding/WebIDE#297]
![image](https://user-images.githubusercontent.com/3430784/31784183-5e84ca4e-b533-11e7-989c-52650cab66c1.png)

其实这个文件是个js脚本，内容见截图下面的terminal

还有就是因为docker部署用的是alpine镜像，很多命令用着不舒服所以我是直接跑的服务，然后发现terminal启动特别慢，刷新后第一次打开terminal要等两三分钟的时间才显示，显示第一个后再开新的就很快了

**Comment by 502647092** [comment]
@bangbang93  活捉大佬

**Comment by tanhe123** [comment]
@bangbang93 第一次打开 terminal 时间过长的 bug 已经修复了，参见：https://github.com/Coding/WebIDE-Frontend/pull/215/files

拉取最新的 docker 镜像即可

**Comment by zhuruiqi** [comment]
fixed
