### ISSUE TITLE
希望在终端可以添加复制黏贴的功能

### ISSUE THREAD

**Issue by 502647092** [Coding/WebIDE#303]
![image](https://user-images.githubusercontent.com/10203793/32156225-0a402018-bd77-11e7-8b33-4c52c9941d3c.png)
终端不能复制黏贴 很痛苦的啊

**Comment by zhuruiqi** [comment]
@502647092 鼠标**选中相应行**右击，可以粘贴。也可以使用快捷键，OS 系统下为 cmd+v，Windows 下为 ctrl+shift+v。

**Comment by 502647092** [comment]
@zhuruiqi 好吧 希望加一些提示吧 习惯性按Ctrl + V 没反应

**Comment by 502647092** [comment]
@zhuruiqi 
![image](https://user-images.githubusercontent.com/10203793/32166876-262e3b04-bda2-11e7-9ede-ef4df54bcf80.png)
这是我操作问题么

**Comment by 502647092** [comment]
![image](https://user-images.githubusercontent.com/10203793/32166955-64fb4c64-bda2-11e7-9eda-2ec7ae9d06c0.png)
我....

**Comment by vangie** [comment]
我们自定义一个右键菜单，然后给出快捷键提示。

**Comment by 502647092** [comment]
@zhuruiqi @vangie Ctrl + Shift + V 确实额可以黏贴 之前问题找到了 该死的百度输入法装了一个什么百度袋鼠 占用了 Ctrl + Shift + V 热键 所以冲突了 一直没黏贴上
