### ISSUE TITLE
Support unzip online and code format

### ISSUE THREAD

**Issue by hackape** [Coding/WebIDE#31]
@cxgreat2014 确认下，你意思是要在虚拟机里能解压文件，以及对代码重新格式化？

**Comment by cxgreat2014** [comment]
嗯，unzip online就像kodexplorer一样能够在线上传代码压缩包到工程目录下，然后右键在线解压，代码重新格式化最好还能自己设定大括号是否换号等等（XD）Thanks

**Comment by vangie** [comment]
@cxgreat2014 感谢您的建议，我们短期没有这个功能计划，如果你愿意贡献一个该功能的PR，可以接受。
