### ISSUE TITLE
光标跑到文件顶部

### ISSUE THREAD

**Issue by 502647092** [Coding/WebIDE#318]
![bug](https://user-images.githubusercontent.com/10203793/33470379-ec26b0e8-d6a2-11e7-836e-9dfcda7abd55.gif)
就是这种情况 好端端的 光标跑到文件顶部了 很影响使用 官方的好像是没问题的(至少暂时没遇到) 开源版本的有这个问题

**Comment by zhuruiqi** [comment]
你好，我们之前没有重现这个问题，请问有固定重现的方法吗？
另外，这个哪个版本？

**Comment by 502647092** [comment]
@zhuruiqi 最新的版本 刚刚pull下来的 至于为什么 应该是保存之后有一个读取操作 还是怎么的 实际上不止是光标跑到上面 还有部分输入也会消失 应该是保存之后有一个读取操作导致的吧 我猜的

**Comment by 502647092** [comment]
@zhuruiqi v0.16.0
还有就是 不知道是不是缓存的问题 Coding的小猴子还是没显示

**Comment by zhuruiqi** [comment]
@502647092 小猴子的问题解决了，需要重新pull一下 v0.16.0 版本。
光标跑到文件顶部的问题未能复现，我们这边会再尝试修复。

**Comment by zhuruiqi** [comment]
@502647092 小猴子的问题解决了，需要重新pull一下 v0.16.1 版本。
光标跑到文件顶部的问题未能复现，我们这边会再尝试修复。

**Comment by 502647092** [comment]
@zhuruiqi emm 说一下情况 我怀疑是开了2个WebIDE导致的 我家里没关IDE 到公司直接打开用 好像会出现 家里电脑没开的话 貌似就不会 具体我测试一下 你那边也可以看下

**Comment by 502647092** [comment]
@zhuruiqi 我重新试了一下 就是因为开了2个WebIDE导致的 我这边两个人同时修改一个项目 但是不是同一个文件夹 就会有这个问题

**Comment by zhuruiqi** [comment]
@502647092 好的，收到。
