### ISSUE TITLE
ubuntu下使用docker安装读取db权限问题

### ISSUE THREAD

**Issue by jiangli373** [Coding/WebIDE#32]
如果想保留这些状态，请确保 $HOME/.coding-ide-home 存在，如果不存在，请手动创建。然后将目录挂载即可：

```js
docker create -p 8080:8080 -v $HOME/.coding-ide-home:/home/coding/.coding-ide-home --name webide webide/webide
```
这种方式执行会报这个问题：

```js
java.sql.SQLException:` opening db: '/home/coding/.coding-ide-home/ide.db': Permission denied
```

**Comment by tanhe123** [comment]
目测是 `$HOME/.coding-ide-home` 不存在，docker 自动创建的 `.coding-ide-home` 目录所有者为 root。

可以尝试执行 'll -d ~/.coding-ide-home` 确认所有者是否为登陆用户。

如果不是，可以使用 `sudo chown -R $USER:$USER ~/.coding-ide-home` 来解决。
