### ISSUE TITLE
v0.16.1版本 后端SQLite报错

### ISSUE THREAD

**Issue by 502647092** [Coding/WebIDE#322]
![image](https://user-images.githubusercontent.com/10203793/33527627-f2b6160e-d88e-11e7-8e9e-2986dc055e44.png)

**Comment by DmuMenDuo** [comment]
老哥，你找到问题原因了吗，我也遇到这个问题了, 如果两个浏览器同时访问同一个spacekey就会出现这个问题？

**Comment by 502647092** [comment]
@DmuMenDuo 暂时没有 不过不影响使用
