### ISSUE TITLE
Vue 文件中的HTML标签 正常情况下提示错误

### ISSUE THREAD

**Issue by 502647092** [Coding/WebIDE#328]
![image](https://user-images.githubusercontent.com/10203793/34559371-96db0540-f17c-11e7-8037-670cfbe4e895.png)

**Comment by zhuruiqi** [comment]
```
<template>
    <section class='container'>
        <h1 class=''title>
            用户反馈
        </h1>
        <span class="txt">版本</span>
        <input v-model='version' class="input" />

        <span class="txt">SessionID</span>
        <input v-model='session_id' class="input" />

        <span class="txt">分数</span>
        <input v-model='score' class="input" />

    </section>
</template>
```

![image](https://user-images.githubusercontent.com/26532614/34864134-baef8d02-f7ad-11e7-8374-b062ab8fb83a.png)

**Comment by 502647092** [comment]
我.... 那.... 为何.... input 为何就不能用 <input></input>

**Comment by vangie** [comment]
https://stackoverflow.com/questions/38498799/input-tag-html-with-close-tag-or-not

**Comment by 502647092** [comment]
= = 谢谢了
