### ISSUE TITLE
WebIDE-Frontend中的task.yaml.tpl配置有问题

### ISSUE THREAD

**Issue by zhanghengjingyu** [Coding/WebIDE#329]
main-packageList       │ fork │ stopped │ 92 │ 0%  │ 0 B       │
 main-project           │ fork │ stopped │ 92 │ 0%  │ 19.4 MB   │
 plugin-debugger        │ fork │ errored │ 0  │ 0%  │ 0 B       │
plugin-platform        │ fork │ errored │ 0  │ 0%  │ 0 B       │
这几个项目在哪里呀，WebIDE-Frontend中没有找到？可以解释下吗？
apps:
- script   : npm
  name     : 'main-project'
  args: start
  exec_mode: fork_mode
  exec_interpreter: node

- script   : npm
  name     : 'main-packageList'
  args: run packageList
  exec_mode: fork_mode
  exec_interpreter: node

- script   : npm
  name     : 'plugin-platform'
  cwd: /Users/zhengxinqi/mycodingjob/webide/WebIDE-Plugin-Platform
  args: start
  env:
    PORT: 4001
  exec_mode: fork_mode
  exec_interpreter: node

- script   : npm
  name     : 'plugin-debugger'
  cwd: /Users/zhengxinqi/mycodingjob/webide/WebIDE-Plugin-Debugger
  args: start

**Comment by 502647092** [comment]
应该是WebIDE的插件 开源版本暂时没有插件

**Comment by zhanghengjingyu** [comment]
那要是没有这几个插件我该如何把前端跑起来呀，卡在这里了

**Comment by zhanghengjingyu** [comment]
如果没有这几个插件我该如何把前端跑起来呀，卡在这里了？

**Comment by 502647092** [comment]
我是直接用Docker跑的 你可以试试

**Comment by sunzp21** [comment]
请问楼主怎么解决的？我在terminal里面用yarn start可以运行，但是前端的shell终端功能用不了，貌似请求地址不对，怎么改啊？

**Comment by 502647092** [comment]
试试Docker版本 #347

**Comment by sunzp21** [comment]
> 试试Docker版本 #347

Dcoker版本确实可以，但是我需要对前端进行修改，Docker版本怎么修改？

**Comment by 502647092** [comment]
> > 试试Docker版本 #347
> 
> Dcoker版本确实可以，但是我需要对前端进行修改，Docker版本怎么修改？

这东西很久没人管了 现在和TX合作之后 估计都去搞新的了
安利你一个新的IDE
https://github.com/theia-ide/theia
在线版本的VSCode

**Comment by KevenYoung** [comment]
这个配置可以不用管的，要跑起来不能只启动前端
要在本项目里（WebIDE 项目）
```
./ide.sh build   # transpile and pack the frontend to webjars
./ide.sh run     # start the backend server
```
前后端同时启动
