### ISSUE TITLE
停止开发了?

### ISSUE THREAD

**Issue by qixin1991** [Coding/WebIDE#337]
Cloud Studio发布了,这个项目还会继续开发下去吗?

**Comment by 502647092** [comment]
反正已经好久没有人理我了 我提了好多的issue

**Comment by summershrimp** [comment]
人手不够吧。 主要精力还在做CloudStudio。。不过反正是开源项目 有啥需要的自己改呗

**Comment by luxcn** [comment]
@502647092 @qixin1991 会继续的，之后把现在的一些新功能整合过来，也会一个一个 bug 来修。

**Comment by 502647092** [comment]
@summershrimp emm 看了源码 有点蒙 还是算了

**Comment by xiaolee55** [comment]
有人说一下怎么单独运行前端吗，我每次都是只出一个界面
