### ISSUE TITLE
执行build脚本报错

### ISSUE THREAD

**Issue by hanabi233** [Coding/WebIDE#339]
yarn install执行到第三步Fetching packages时候报错，信息如下：
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/hackape/socket.io-client
Directory: D:\work\opensource\WebIDE\frontend
Output:
remote: Repository not found.
fatal: repository 'https://github.com/hackape/socket.io-client/' not found
请问应该如何解决？

**Comment by hanabi233** [comment]
@zhuruiqi

**Comment by 502647092** [comment]
推荐使用Docker部署

**Comment by hanabi233** [comment]
@502647092 需求是对后端源码做一些定制，环境没有docker化，native server方式现在不可行了吗？
socket.io-client-legacy这一依赖在淘宝npm镜像有条目而无下载入口，如何替换这一失效源？

**Comment by zhuruiqi** [comment]
@hanabi233 @502647092 之前已经修复过，麻烦 pull 一下试试。

**Comment by hanabi233** [comment]
@zhuruiqi 在WebIDE项目下执行pull吗？更新了submodule，大项目也pull了，执行ide.sh build还是报相同错误。需要到三个子模块下分别pull？

**Comment by zhuruiqi** [comment]
@hanabi233 这边又更新了一下 submodule，麻烦在更新一下主项目和 submodule 
`git submodule update`

**Comment by hanabi233** [comment]
@zhuruiqi 请问更新内容push到github了吗？主项目和submodule都更新了依旧报相同错，全部删除重新拉代码也是一样。观察了主项目和三个子项目，最近都没有commit

**Comment by zhuruiqi** [comment]
@hanabi233 我这里试了一下是可以的，你那边是什么环境下跑的？
![image](https://user-images.githubusercontent.com/26532614/44570066-1f3ce500-a7af-11e8-8aa0-2ae327538568.png)

**Comment by 502647092** [comment]
@zhuruiqi 弱弱的问下开源版WebIDE能把新的编辑器更新一下嘛

**Comment by zhuruiqi** [comment]
@502647092 暂时没有这个计划。而且开源版没有插件，也没有语言服务，有了新版编辑器也用不了语言服务和代码提示。

**Comment by rikkizhu** [comment]
@502647092 暂时没有这个计划。开源版没有插件，后端也没有语言服务，有了新版编辑器也用不了语言服务和代码提示。

**Comment by rikkizhu** [comment]
@hanabi233 这边又重新提交了一下，麻烦再试一下。如果还不可以的话，推荐使用 ubuntu 虚拟机来跑。

**Comment by hanabi233** [comment]
@zhuruiqi 前端项目更新之后编译成功了，观察了一下ide.sh，定义了三个命令build、run和docker，命令行下如何停止服务呢
另外，如果使用本地IDE打开代码，请问应该如何调试

**Comment by rikkizhu** [comment]
@hanabi233 `control + c `不可以吗，如果挂在了后台，可以用 windows 的任务管理器。

**Comment by rikkizhu** [comment]
关于本地 IDE 的调试问题，这边没能理解您的问题。具体使用可以查看您所使用的本地 IDE 的使用文档
