### ISSUE TITLE
指引文档稍微弱了点，无法很快上手

### ISSUE THREAD

**Issue by landy2014** [Coding/WebIDE#34]
不管是中文还是英文说明文档，都显得稍微弱了点，指引性不够强，希望能增强些。比如安装运行环境，安装能够跑起来的demo代码等等。

**Comment by tanhe123** [comment]
文档，我们会逐渐丰富起来。

如果只是想跑起来试试，推荐使用 [docker](https://github.com/Coding/WebIDE/wiki/Docker-Server.zh#%E4%BD%BF%E7%94%A8-docker-%E5%91%BD%E4%BB%A4) 版本。

如果不会安装 Docker，可以参考[官方文档](https://docs.docker.com/engine/installation/)，国内推荐使用 DaoCloud 加速[安装](https://get.daocloud.io/#install-docker-for-mac-windows)、加速下载[镜像](https://www.daocloud.io/mirror.html#accelerator-doc)。

**Comment by landy2014** [comment]
恩，只是给点建议，文档在开源软件来说非常重要。
我折腾了一下，跑起来了。谢谢
