### ISSUE TITLE
本地Server启动，页面空白

### ISSUE THREAD

**Issue by hanabi233** [Coding/WebIDE#341]
本地Server模式编译启动成功，第一次出现了界面，然而ctrl+C之后再执行./ide.sh run，启动之后页面空白，标题栏显示正常
请问是什么问题@zhuruiqi

**Comment by hanabi233** [comment]
@zhuruiqi 请问能介绍一下将前端资源打成jar，后端通过依赖前端包达到单纯启动后端的springboot应用就全盘启动效果的方法吗（后端项目的pom中并没有webjars的依赖，特此请教）

**Comment by hanabi233** [comment]
异常原因定位为4个异常URL请求
打开127.0.0.1:8080时候，有五个请求
127.0.0.1:8080的GET请求成功，描述了页面结构并显式定义了head内容
http://webpackruntime.8de2cb1ce36c7d04f768.js/
http://vendor.6c9d2875d844b6c4e632.js/
http://workspaces.3f88bc58234906fa63e9.js/
http://favicon.ico/
以上静态资源在项目目录中都可以找到，运行时的请求路径异常原因不明

**Comment by rikkizhu** [comment]
“ctrl+C之后再执行./ide.sh run，启动之后页面空白”的问题没能复现，估计是运行环境有差异，推荐用 ubuntu 虚拟机，windows 下我们这边没跑起来过。
后端项目的 pom 中是有 webjars  依赖的，要找一找，可能是其他依赖的间接依赖。
