### ISSUE TITLE
shell（终端）打不开

### ISSUE THREAD

**Issue by tigergm** [Coding/WebIDE#349]
请教，使用native的方式运行了WebIDE，都成功，访问临时服务时候其他功能都没问题，就是终端点击后，
没有形成一个有效的shell，只有一个空白的面板，不响应任何输入，也没有初始任何shell。请问需要什么前提条件或预先配置么？我就是按照官方步骤一步一步搞的，是不是需要一些额外的工作？反正后台没看到有报错的log。
（另外，我使用了CloudIDE部署的，是不是有一些端口受限？）

**Comment by tigergm** [comment]
刚才看了一下浏览器的console，可能与socket.io的监听有关。。是不是部署在Cloud Studio上的应用会有一些屏蔽，以后换到本地开发环境测试测试。
VM11200:6 GET https://hlglty-8080-ovsyee.dev.ide.live/socket.io/?EIO=3&transport=polling&t=MYd8UC9 404 ()

**Comment by zisedexiao** [comment]
请问解决了吗？我部署在本地虚拟机也是不行，浏览器console一直报404错误

**Comment by 502647092** [comment]
Docker 版本了解下 #347

**Comment by tigergm** [comment]
我没有尝试虚拟机，404是不是端口部署的有问题。希望这个开源项目能够持续下去，已经在Cloud Studio安家了，不大需要自己去构建一个WebIDE，这个问题标定关闭，这个产品更好发展，未来能够在商用做合作更好。
