### ISSUE TITLE
docker运行不成功

### ISSUE THREAD

**Issue by syw0602** [Coding/WebIDE#49]
docker 运行后，点击Creating之后没有反应

chrome调试有JS报错

如图：

![image](https://cloud.githubusercontent.com/assets/2759752/19394053/fe990074-9269-11e6-851a-2145399d82e4.png)

**Comment by syw0602** [comment]
直接在线测：

http://54.255.139.180:8080/

**Comment by tanhe123** [comment]
1. 将 ssh key 上传到 github、Coding 或其它代码托管平台
2. 使用 ssh url 进行 clone

**Comment by syw0602** [comment]
@tanhe123 明白了
