### ISSUE TITLE
安装异常

### ISSUE THREAD

**Issue by jnan77** [Coding/WebIDE#5]
[root@VM_228_165_centos WebIDE-Workspace]# git submodule update
fatal: 引用不是一个树：ac73909650a9afcc3fe8fe3b252b3734ed6d3adc
fatal: 引用不是一个树：784f580d52af9867a860c73075ab0064d251c48d
无法在子模组路径 'backend' 中检出 'ac73909650a9afcc3fe8fe3b252b3734ed6d3adc'
无法在子模组路径 'frontend' 中检出 '784f580d52af9867a860c73075ab0064d251c48d'

**Comment by tanhe123** [comment]
先 git pull 一下，再试试
