### ISSUE TITLE
git submodule update failed

### ISSUE THREAD

**Issue by nobodyiam** [Coding/WebIDE#6]
git submodule update

Cloning into 'backend'...
remote: Counting objects: 201, done.
remote: Compressing objects: 100% (155/155), done.
remote: Total 201 (delta 26), reused 201 (delta 26)
Receiving objects: 100% (201/201), 1.75 MiB | 260.00 KiB/s, done.
Resolving deltas: 100% (26/26), done.
Checking connectivity... done.
fatal: reference is not a tree: ac73909650a9afcc3fe8fe3b252b3734ed6d3adc
Cloning into 'frontend'...
remote: Counting objects: 124, done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 124 (delta 4), reused 120 (delta 3)
Receiving objects: 100% (124/124), 50.87 KiB | 0 bytes/s, done.
Resolving deltas: 100% (4/4), done.
Checking connectivity... done.
fatal: reference is not a tree: 784f580d52af9867a860c73075ab0064d251c48d
Cloning into 'frontend-webjars'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (6/6), done.
Checking connectivity... done.
Submodule path 'frontend-webjars': checked out '93a712b31b5f8831ec14c719fca46764968e3b69'
Unable to checkout 'ac73909650a9afcc3fe8fe3b252b3734ed6d3adc' in submodule path 'backend'
Unable to checkout '784f580d52af9867a860c73075ab0064d251c48d' in submodule path 'frontend'

**Comment by nobodyiam** [comment]
git submodule init 执行正常

Submodule 'backend' (git://git.coding.net/coding/WebIDE-Backend.git) registered for path 'backend'
Submodule 'frontend' (git://git.coding.net/coding/WebIDE-Frontend.git) registered for path 'frontend'
Submodule 'frontend-webjars' (git://git.coding.net/coding/WebIDE-Frontend-Webjars.git) registered for path 'frontend-webjars'

**Comment by tanhe123** [comment]
git pull 下，再试试
