### ISSUE TITLE
文件上传

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#88]
桌面文件拖拽到文件树能上传到相应目录里

## 右键菜单上传
- [x] 1. 目录右键菜单里包含“文件上传...”

- [x] ## 拖拽上传
- [x] 1. 未展开目录悬停以后能展开
2. 拖拽到某个文件上放释放后，上传到同级目录
3. 拖拽到文件树才响应请求，拖拽到文件数空白区域，文件上传到项目根目录
4. 拖拽到上线边缘处能触发滚动出不可见区域

- [x] ## 进度显示
1. 在状态栏显示上传进度
2. 如果状态栏有多条消息，以滚动方式显示

**Comment by vangie** [comment]
拖拽和进度显示还没有

**Comment by blizzardzheng** [comment]
这个issue还差文件树的拖拽展开部分

**Comment by zhuruiqi** [comment]
上传进度显示没有实现，上传较大的文件无反应#212。先关闭此任务
