### ISSUE TITLE
为 terminal 和 git history 提供直接的开启方法

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#96]
![2016-12-27 3 24 52](https://cloud.githubusercontent.com/assets/1388582/21493860/b5b34efa-cc48-11e6-8df1-d6cd0e8528da.png)

通过菜单打开太麻烦了，在状态栏上部直接提供开启入口，效果和平台版一致

**Comment by KevenYoung** [comment]
现在已经有了
