### ISSUE TITLE
Git Branch 的若干改进

### ISSUE THREAD

**Issue by vangie** [Coding/WebIDE#97]
* Git 菜单缺少 Git Branch的入口 
![826026ce-46df-4183-b5ad-06e973abecc5](https://cloud.githubusercontent.com/assets/1388582/21494005/65039202-cc49-11e6-8e22-207902e9f956.png)

* branch子菜单缺少了两项
![2016-12-27 3 31 09](https://cloud.githubusercontent.com/assets/1388582/21494041/9e39d7ca-cc49-11e6-93aa-3d420c9d4b50.png)
![2016-12-27 3 31 20](https://cloud.githubusercontent.com/assets/1388582/21494042/a0a2a35c-cc49-11e6-96b4-b2baac7397af.png)

* 缺少同步功能
![image](https://cloud.githubusercontent.com/assets/1388582/21494088/fc497d34-cc49-11e6-9b43-7e5475f3807e.png)

* UI细节改进
![image](https://cloud.githubusercontent.com/assets/1388582/21494079/e74ac6ea-cc49-11e6-83ca-e91c2b67b479.png)

**Comment by blizzardzheng** [comment]
@kevenyoung 这个任务你前面两个点你做了吗

**Comment by KevenYoung** [comment]
@blizzardzheng 没呢

**Comment by blizzardzheng** [comment]
@KevenYoung 好的 那我做掉

**Comment by blizzardzheng** [comment]
- [x] 样式调整
- [ ] git branch功能
